<?php

use App\Core\Helper;
use App\Database\CSVUploader;
use App\Media\FileUpload;
use App\Notifiable\Mailable;
use App\School\AcademicYear;

include_once './includes/header.php';

if (!Helper::isActivated($schoolId) || $sms_role == $TEACHER) {
    Helper::showNotPermittedPage();
}

// upload students data via CSV
$error = [];
$success = "";

if (isset($_GET['request_mail'])) {
    try {
        $email = Helper::getSchoolEmail($schoolId);
        $classData = Helper::loadClass($schoolId);
        $dataClass = [];
        if ($classData) {
            foreach ($classData as $data) {
                $dataClass[] = [$data->className, $data->classId];
            }
        }
        $mail = new Mailable('sensitive', [
            'schoolId' => $schoolId,
            'academicYear' => AcademicYear::getCurrentYearId($schoolId),
            'classData' => $dataClass,
            'to' => $email,
            'name' => Helper::getSchoolName($schoolId),
            'fromName' => DEFAULT_FULLNAME,
            'from' => DEFAULT_FROM,
            'subject' => 'Please do not share this with anyone'
        ]);

        $sent = $mail->build()->send();
        $sent ? $success = "Mail was sent to {$email}" : $error[] = "Error occurred while sending mail to {$email}";
    } catch (Exception $e) {
        $error[] = $e->getMessage();
    }
}

if ($_SERVER['REQUEST_METHOD'] == "POST") {
    $file = $_FILES['csvfile'];
    if ($file && $file['name'] != "") {
        try {
            $file = FileUpload::uploadFile("./assets/students/", $file);
            $fields = ['fullname', 'class', 'academicYear', 'gender', 'dob', 'phone', 'address', 'admissionno', 'bloodgroup', 'parphone', 'emergcon', 'medical', 'school', 'paremail', 'email', 'password', 'mysubjects'];
            $csvUploader = new CSVUploader("./assets/students/" . $file, 'students', $fields);
            $csvUploader->uploadToDB();
            $success = "Students Data has been uploaded to our database <i class='mdi
            mdi-check-circle text-success'></i>";
            @@unlink("./assets/students/" . $file);
        } catch (Exception $e) {
            $error[] = $e->getMessage();
        }
    } else {
        $error[] = "Please select a file to upload";
    }
}


?>
<div class="container-scroller">
    <?php include_once './includes/navbar.php'; ?>

    <div class="main-panel">
        <br>
        <?php
        if (!empty($error)) {
            echo "<div class='alert alert-danger'>";
            foreach ($error as $e) {
                echo $e . "<br>";
            }
            echo "</div>";
        }

        if ($success != "") {
            echo "<div class='alert alert-success'>$success</div>";
        }
        ?>
        <div class="content-wrapper pb-0">
            <h2 class="text">Upload Students Data</h2>
            <p><b>Instructions</b>:<br>
            <ul>
                <li>Download the template file below so as to match our database fields</li>
                <li>Once data has been filled in template file:
                    <ul>
                        <li>Save it as a CSV document</li>
                        <li>Click the upload button below to select and upload it</li>
                    </ul>
                </li>
                <li>For sensitive IDs like: class, academicYear, school: <ul>
                        <li>Request your school's sensitive IDs <a href="?request_mail">here</a></li>
                    </ul>
                </li>
                <li>For columns that are generated by US or not required, please leave then empty</li>
                <li>List of required fields:
                    <ul>
                        <li>fullname</li>
                        <li>class</li>
                        <li>academicYear</li>
                        <li>gender [M or F]</li>
                        <li>school</li>
                        <li>paremail [Parent's Email]</li>
                        <li>email & password [If you opted for online assessments. Set password to "1234" or whatever default you choose]</li>
                    </ul>
                </li>
                <li>Download Template File <a href="./student_upload_template_mercury_sms.csv" download="mercury_students_upload_template.csv">here</a></li>
            </ul>
            </p>

            <form action="" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <input type="file" name="csvfile" id="csvfile" accept=".csv">
                </div>
                <div class="form-group">
                    <input type="submit" value="Upload CSV File" class="btn btn-primary">
                </div>
            </form>

        </div>
        <?php include_once './includes/footer.php'; ?>